name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update system
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Install tmate
        run: |
          sudo apt-get install -y tmate

      - name: Start tmate session
        run: |
          tmate -F &   # Start in foreground mode in background
          sleep 5
          echo "SSH connection:"
          tmate display -p '#{tmate_ssh}'
          echo "Web connection:"
          tmate display -p '#{tmate_web}'

      - name: Keep session alive for 2 hours
        run: sleep 7200
